blank_issues_enabled: false
contact_links:
  - name: ğŸ“š æ–‡æ¡£
    url: https://github.com/zhinjs/segment-matcher#readme
    about: è¯·å…ˆæŸ¥çœ‹æ–‡æ¡£ï¼Œäº†è§£å¦‚ä½•ä½¿ç”¨ segment-matcher
  - name: ğŸ’¬ è®¨è®º
    url: https://github.com/zhinjs/segment-matcher/discussions
    about: åœ¨è®¨è®ºåŒºæé—®æˆ–åˆ†äº«æƒ³æ³•
  - name: ğŸ› å·²çŸ¥é—®é¢˜
    url: https://github.com/zhinjs/segment-matcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug
    about: æŸ¥çœ‹å·²çŸ¥çš„ Bug åˆ—è¡¨ 